backend:
  name: git-gateway
  branch: main

# تفعيل الوضع التحريري
publish_mode: editorial_workflow

# مجلد الوسائط
media_folder: "assets/images"
public_folder: "/assets/images"

# اللغة
locale: 'ar'

# المجموعات
collections:
  # الخدمات
  - name: "services"
    label: "الخدمات"
    folder: "_data/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "الوصف", name: "description", widget: "text"}
      - {label: "الأيقونة", name: "icon", widget: "string", hint: "مثل: fas fa-palette"}
      - {label: "التصنيف", name: "category", widget: "select", options: ["احترافي", "إبداعي", "تقني", "شخصي", "تسويقي", "مهني"]}
      - {label: "الترتيب", name: "order", widget: "number", default: 1}
      - {label: "مفعل", name: "active", widget: "boolean", default: true}

  # المعرض
  - name: "portfolio"
    label: "معرض الأعمال"
    folder: "_data/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "الوصف", name: "description", widget: "text"}
      - {label: "الصورة", name: "image", widget: "image"}
      - {label: "التصنيف", name: "category", widget: "select", options: ["identity", "marketing", "websites", "invitations"]}
      - {label: "العميل", name: "client", widget: "string", required: false}
      - {label: "تاريخ الإنجاز", name: "date", widget: "datetime"}
      - {label: "عمل مميز", name: "featured", widget: "boolean", default: false}
      - {label: "مفعل", name: "active", widget: "boolean", default: true}
      - {label: "رابط العمل", name: "link", widget: "string", required: false}

  # آراء العملاء
  - name: "testimonials"
    label: "آراء العملاء"
    folder: "_data/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "اسم العميل", name: "client_name", widget: "string"}
      - {label: "المسمى الوظيفي", name: "client_title", widget: "string"}
      - {label: "نص الرأي", name: "review", widget: "text"}
      - {label: "التقييم", name: "rating", widget: "number", min: 1, max: 5, default: 5}
      - {label: "صورة العميل", name: "avatar", widget: "image", required: false}
      - {label: "التاريخ", name: "date", widget: "datetime"}
      - {label: "مفعل", name: "active", widget: "boolean", default: true}

  # الصفحات
  - name: "pages"
    label: "الصفحات"
    files:
      - label: "الصفحة الرئيسية"
        name: "home"
        file: "_data/home.yml"
        fields:
          - {label: "العنوان الرئيسي", name: "hero_title", widget: "string"}
          - {label: "العنوان الفرعي", name: "hero_subtitle", widget: "string"}
          - {label: "وصف الصفحة الرئيسية", name: "hero_description", widget: "text"}
          
      - label: "صفحة من أنا"
        name: "about"
        file: "_data/about.yml"
        fields:
          - {label: "العنوان", name: "title", widget: "string"}
          - {label: "الوصف", name: "description", widget: "text"}
          - {label: "المهارات", name: "skills", widget: "list", fields: [
              {label: "اسم المهارة", name: "name", widget: "string"},
              {label: "النسبة", name: "percentage", widget: "number", min: 0, max: 100},
              {label: "الأيقونة", name: "icon", widget: "string"}
            ]}

  # الإعدادات العامة
  - name: "settings"
    label: "الإعدادات"
    files:
      - label: "معلومات الاتصال"
        name: "contact"
        file: "_data/contact.yml"
        fields:
          - {label: "البريد الإلكتروني", name: "email", widget: "string"}
          - {label: "رقم الهاتف", name: "phone", widget: "string"}
          - {label: "رقم الواتساب", name: "whatsapp", widget: "string"}
          - {label: "العنوان", name: "address", widget: "string"}
          - {label: "روابط التواصل الاجتماعي", name: "social", widget: "object", fields: [
              {label: "إنستغرام", name: "instagram", widget: "string"},
              {label: "تويتر", name: "twitter", widget: "string"},
              {label: "بينتريست", name: "pinterest", widget: "string"}
            ]}

